- name: Create Kiosk Script
  copy: 
    dest: /home/digipi/kiosk.sh
    content: |
      #!/bin/bash
      chromium-browser --noerrdialogs --disable-infobars --kiosk http://your-url-here --incognito --disable-translate
    owner: digipi
    group: digipi
    mode: '0755'
  tags: 
  - scripts


- name: Update autostart file
  lineinfile:
    path: /home/digipi/.config/lxsession/LXDE-pi/autostart
    line: "@/home/digipi/kiosk.sh"
    create: yes
    owner: digipi
    group: digipi
  tags: 
  - scripts
