- name: Create Kiosk Script
  copy: 
    dest: /home/pi/kiosk.sh
    content: |
      #!/bin/bash
      chromium-browser --noerrdialogs --disable-infobars --kiosk http://your-url-here --incognito --disable-translate
    owner: pi
    group: pi
    mode: '0755'
  tags: 
  - scripts


- name: Update autostart file
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    line: "@/home/pi/kiosk.sh"
    create: yes
  tags: 
  - scripts
